apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp-pod
  ports:
    - name: nginx-container
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: multitool-container
      protocol: TCP
      port: 9002
      targetPort: 8080